### ISSUE TITLE
'validate' is showing hash as orphaned if there are multiple entries per blockheight

### ISSUE THREAD

**Issue by gitmachtl** [cardano-community/cncli#8] opened 2022-07-23 13:01 UTC
cncli 5.0.3

In scenarios with for example height battles, sometimes hashes are stored as orphaned in the cncli database together with one of the same hash nor marked as orphaned (the resolved outcome of a battle for example), but the 'validate' command is still showing such a hash as orphaned. Should be reported as a valid hash at that point.

**Comment by AndrewWestberg** [comment] 2022-07-23 13:13
The issue is that the validate query is grabbing the first hash that matches from the db. Adding an ORDER clause to the query to return non-orphaned hashes first should resolve it.

**Comment by AndrewWestberg** [comment] 2022-07-23 13:43
Fixed in v5.0.4

**Closed as completed by AndrewWestberg** 2022-07-23 13:43 UTC
